import { Galpone, Lote, RegistroProductivo, Alerta, Venta, Usuario, Vacunacion, Tratamiento, Sensor, Reporte } from './types';

export const galpones: Galpone[] = [
  {
    id: 'G001',
    nombre: 'Galpón 1 - Norte',
    capacidad: 30000,
    gallinasActuales: 28500,
    loteActual: 'A-2026',
    produccionDiaria: 27500,
    estadoSanitario: 'Excelente',
    estadoAmbiental: 'Óptimo',
    consumoAlimento: 45,
    consumoAgua: 65,
    alertasActivas: 0,
    eficiencia: 96.5,
    temperatura: 22,
    humedad: 65,
  },
  {
    id: 'G002',
    nombre: 'Galpón 2 - Centro',
    capacidad: 45000,
    gallinasActuales: 42000,
    loteActual: 'B-2026',
    produccionDiaria: 39900,
    estadoSanitario: 'Bueno',
    estadoAmbiental: 'Aceptable',
    consumoAlimento: 68,
    consumoAgua: 98,
    alertasActivas: 1,
    eficiencia: 95.1,
    temperatura: 23,
    humedad: 68,
  },
  {
    id: 'G003',
    nombre: 'Galpón 3 - Sur',
    capacidad: 60000,
    gallinasActuales: 58000,
    loteActual: 'C-2025',
    produccionDiaria: 52200,
    estadoSanitario: 'Regular',
    estadoAmbiental: 'Alerta',
    consumoAlimento: 92,
    consumoAgua: 132,
    alertasActivas: 2,
    eficiencia: 90.0,
    temperatura: 25,
    humedad: 72,
  },
  {
    id: 'G004',
    nombre: 'Galpón 4 - Este',
    capacidad: 25000,
    gallinasActuales: 24000,
    loteActual: 'D-2025',
    produccionDiaria: 22560,
    estadoSanitario: 'Excelente',
    estadoAmbiental: 'Óptimo',
    consumoAlimento: 38,
    consumoAgua: 55,
    alertasActivas: 0,
    eficiencia: 94.0,
    temperatura: 21,
    humedad: 63,
  },
];

export const lotes: Lote[] = [
  {
    id: 'L001',
    codigo: 'A-2026',
    galpone: 'G001',
    fechaIngreso: '2025-09-15',
    edad: 262,
    cantidadAves: 28500,
    etapa: 'Postura',
    produccionAcumulada: 7215000,
    estadoSanitario: 'Excelente',
    vidaUtilEstimada: 365,
    fechaRecambio: '2026-09-15',
  },
  {
    id: 'L002',
    codigo: 'B-2026',
    galpone: 'G002',
    fechaIngreso: '2025-11-01',
    edad: 214,
    cantidadAves: 42000,
    etapa: 'Postura',
    produccionAcumulada: 8379600,
    estadoSanitario: 'Bueno',
    vidaUtilEstimada: 365,
    fechaRecambio: '2026-11-01',
  },
  {
    id: 'L003',
    codigo: 'C-2025',
    galpone: 'G003',
    fechaIngreso: '2024-11-01',
    edad: 579,
    cantidadAves: 58000,
    etapa: 'Descarte',
    produccionAcumulada: 20879400,
    estadoSanitario: 'Regular',
    vidaUtilEstimada: 500,
    fechaRecambio: '2026-08-15',
  },
  {
    id: 'L004',
    codigo: 'D-2025',
    galpone: 'G004',
    fechaIngreso: '2025-08-20',
    edad: 287,
    cantidadAves: 24000,
    etapa: 'Postura',
    produccionAcumulada: 6427200,
    estadoSanitario: 'Excelente',
    vidaUtilEstimada: 365,
    fechaRecambio: '2026-08-20',
  },
];

export const registrosProductivos: RegistroProductivo[] = [
  {
    id: 'RP001',
    fecha: '2026-06-03',
    galpone: 'G001',
    lote: 'A-2026',
    totalHuevos: 27500,
    huevsAptos: 26620,
    huevsRotos: 550,
    huevsSucios: 330,
    huevsDescartados: 0,
    eficiencia: 96.8,
    observaciones: 'Producción normal',
    responsable: 'Juan García',
  },
  {
    id: 'RP002',
    fecha: '2026-06-03',
    galpone: 'G002',
    lote: 'B-2026',
    totalHuevos: 39900,
    huevsAptos: 37901,
    huevsRotos: 1196,
    huevsSucios: 803,
    huevsDescartados: 0,
    eficiencia: 95.0,
    observaciones: 'Ligero descenso en producción',
    responsable: 'Carlos López',
  },
  {
    id: 'RP003',
    fecha: '2026-06-03',
    galpone: 'G003',
    lote: 'C-2025',
    totalHuevos: 52200,
    huevsAptos: 46980,
    huevsRotos: 1304,
    huevsSucios: 3916,
    huevsDescartados: 0,
    eficiencia: 90.0,
    observaciones: 'Mayor tasa de huevos sucios',
    responsable: 'María Rodríguez',
  },
  {
    id: 'RP004',
    fecha: '2026-06-03',
    galpone: 'G004',
    lote: 'D-2025',
    totalHuevos: 22560,
    huevsAptos: 21206,
    huevsRotos: 451,
    huevsSucios: 903,
    huevsDescartados: 0,
    eficiencia: 94.0,
    observaciones: 'Producción estable',
    responsable: 'Pedro Martínez',
  },
];

export const alertas: Alerta[] = [
  {
    id: 'AL001',
    tipo: 'Productiva',
    prioridad: 'Alta',
    fecha: '2026-06-03',
    galpone: 'G003',
    lote: 'C-2025',
    descripcion: 'Tasa de huevos sucios elevada (7.5% vs 3% normal)',
    estado: 'Activa',
    accionRecomendada: 'Revisar sistema de nidales y limpieza',
  },
  {
    id: 'AL002',
    tipo: 'Ambiental',
    prioridad: 'Media',
    fecha: '2026-06-02',
    galpone: 'G003',
    descripcion: 'Temperatura fuera de rango (25°C vs 22-23°C óptimo)',
    estado: 'En revisión',
    accionRecomendada: 'Verificar ventilación y considerar aumentar cortinas',
  },
  {
    id: 'AL003',
    tipo: 'Sanitaria',
    prioridad: 'Crítica',
    fecha: '2026-06-01',
    galpone: 'G002',
    lote: 'B-2026',
    descripcion: 'Vacunación de Newcastle pendiente',
    estado: 'Activa',
    accionRecomendada: 'Programar vacunación inmediatamente',
  },
  {
    id: 'AL004',
    tipo: 'Consumo',
    prioridad: 'Media',
    fecha: '2026-06-03',
    galpone: 'G002',
    descripcion: 'Consumo de alimento anormal (incremento del 8%)',
    estado: 'Activa',
    accionRecomendada: 'Revisar calidad del alimento y estado de las aves',
  },
];

export const ventas: Venta[] = [
  {
    id: 'V001',
    fecha: '2026-06-01',
    cliente: 'Supermercados Éxito',
    cantidadHuevos: 15000,
    categoria: 'Extra',
    precioUnitario: 0.18,
    total: 2700,
    estadoPago: 'Pagado',
    observaciones: 'Entrega a tiempo',
  },
  {
    id: 'V002',
    fecha: '2026-06-02',
    cliente: 'Distribuidora Central',
    cantidadHuevos: 25000,
    categoria: 'Primera',
    precioUnitario: 0.15,
    total: 3750,
    estadoPago: 'Pagado',
    observaciones: 'Compra regular',
  },
  {
    id: 'V003',
    fecha: '2026-06-03',
    cliente: 'Panadería La Mejor',
    cantidadHuevos: 3000,
    categoria: 'Segunda',
    precioUnitario: 0.12,
    total: 360,
    estadoPago: 'Pendiente',
    observaciones: 'Primer envío',
  },
  {
    id: 'V004',
    fecha: '2026-06-03',
    cliente: 'Hotel Resort Premium',
    cantidadHuevos: 5000,
    categoria: 'Extra',
    precioUnitario: 0.20,
    total: 1000,
    estadoPago: 'Pagado',
    observaciones: 'Contrato mensual',
  },
];

export const usuarios: Usuario[] = [
  {
    id: 'U001',
    nombre: 'Carlos Rodríguez',
    email: 'carlos@granja.com',
    rol: 'Admin',
    estado: 'Activo',
    ultimoAcceso: '2026-06-03',
  },
  {
    id: 'U002',
    nombre: 'Juan García',
    email: 'juan@granja.com',
    rol: 'Gerente',
    estado: 'Activo',
    ultimoAcceso: '2026-06-03',
  },
  {
    id: 'U003',
    nombre: 'María Rodríguez',
    email: 'maria@granja.com',
    rol: 'Supervisor',
    estado: 'Activo',
    ultimoAcceso: '2026-06-02',
  },
  {
    id: 'U004',
    nombre: 'Pedro Martínez',
    email: 'pedro@granja.com',
    rol: 'Operario',
    estado: 'Activo',
    ultimoAcceso: '2026-06-03',
  },
  {
    id: 'U005',
    nombre: 'Dr. Luis Veterinario',
    email: 'luis@granja.com',
    rol: 'Veterinario',
    estado: 'Activo',
    ultimoAcceso: '2026-06-01',
  },
];

export const vacunaciones: Vacunacion[] = [
  {
    id: 'VAC001',
    fecha: '2025-12-15',
    lote: 'B-2026',
    vacuna: 'Newcastle',
    dosis: '0.5ml',
    responsable: 'Dr. Luis',
    observaciones: 'Aplicado correctamente',
  },
  {
    id: 'VAC002',
    fecha: '2025-12-20',
    lote: 'B-2026',
    vacuna: 'Bronquitis Infecciosa',
    dosis: '0.5ml',
    responsable: 'Dr. Luis',
    observaciones: 'Sin reacciones adversas',
  },
  {
    id: 'VAC003',
    fecha: '2026-01-10',
    lote: 'A-2026',
    vacuna: 'Newcastle',
    dosis: '0.5ml',
    responsable: 'Dr. Luis',
    observaciones: 'Refuerzo aplicado',
  },
];

export const tratamientos: Tratamiento[] = [
  {
    id: 'TRT001',
    fecha: '2026-05-28',
    lote: 'C-2025',
    tipo: 'Preventivo',
    nombre: 'Vitaminas y electrolitos',
    dosis: '1kg/1000L agua',
    responsable: 'Dr. Luis',
    fechaFin: '2026-06-04',
  },
  {
    id: 'TRT002',
    fecha: '2026-06-01',
    lote: 'B-2026',
    tipo: 'Preventivo',
    nombre: 'Probióticos',
    dosis: '500g/tonelada alimento',
    responsable: 'Dr. Luis',
    fechaFin: '2026-06-15',
  },
];

export const sensores: Sensor[] = [
  {
    id: 'SEN001',
    tipo: 'Temperatura',
    galpone: 'G001',
    estado: 'Conectado',
    ultimaLectura: 22.5,
    fecha: '2026-06-03',
  },
  {
    id: 'SEN002',
    tipo: 'Temperatura',
    galpone: 'G002',
    estado: 'Conectado',
    ultimaLectura: 23.8,
    fecha: '2026-06-03',
  },
  {
    id: 'SEN003',
    tipo: 'Alimento',
    galpone: 'G001',
    estado: 'Conectado',
    ultimaLectura: 2450,
    fecha: '2026-06-03',
  },
  {
    id: 'SEN004',
    tipo: 'Agua',
    galpone: 'G002',
    estado: 'Desconectado',
    ultimaLectura: 0,
    fecha: '2026-06-02',
  },
];

export const reportes: Reporte[] = [
  {
    id: 'REP001',
    tipo: 'Productivo',
    fecha: '2026-06-03',
    galpone: 'G001',
    lote: 'A-2026',
    titulo: 'Reporte Productivo Junio 2026',
    descripcion: 'Análisis de producción del galpón 1',
    estado: 'Generado',
  },
  {
    id: 'REP002',
    tipo: 'Sanitario',
    fecha: '2026-06-03',
    titulo: 'Reporte Sanitario General',
    descripcion: 'Estado general de vacunaciones y tratamientos',
    estado: 'Generado',
  },
];
